
#ifndef ZEPHYR_MODULES_CANOPENNODE_CO_ZEPHYR_CONFIG_H
#define ZEPHYR_MODULES_CANOPENNODE_CO_ZEPHYR_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <zephyr/autoconf.h> /* CONFIG_* */
#include <zephyr/sys/util.h> /* IS_ENABLED, BIT */

/* Small helpers to OR flags conditionally */
#define ZBIT(flag, cfgsym) (IS_ENABLED(cfgsym) ? (flag) : 0)
#define ZVAL(cfgsym)       (cfgsym)

/* ---------- NMT / Heartbeat producer ---------- */
#define CO_CONFIG_NMT                                                                              \
	(ZBIT(CO_CONFIG_NMT_CALLBACK_CHANGE, CONFIG_CANOPENNODE_NMT_CALLBACK_CHANGE) |             \
	 ZBIT(CO_CONFIG_NMT_MASTER, CONFIG_CANOPENNODE_NMT_MASTER) |                               \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_NMT_CALLBACK) |                      \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_NMT_TIMERNEXT))

/* Optional: first heartbeat delay (ms) if you wire it in app code */
#define CO_NMT_FIRST_HB_TIME_MS CONFIG_CANOPENNODE_NMT_FIRST_HB_TIME_MS

/* NMT state machine control flags */
#define CO_NMT_STARTUP_TO_OPERATIONAL  IS_ENABLED(CONFIG_CANOPENNODE_NMT_STARTUP_TO_OPERATIONAL)
#define CO_NMT_ERR_ON_BUSOFF_HB        IS_ENABLED(CONFIG_CANOPENNODE_NMT_ERR_ON_BUSOFF_HB)
#define CO_NMT_ERR_ON_ERR_REG          IS_ENABLED(CONFIG_CANOPENNODE_NMT_ERR_ON_ERR_REG)
#define CO_NMT_ERR_TO_STOPPED          IS_ENABLED(CONFIG_CANOPENNODE_NMT_ERR_TO_STOPPED)
#define CO_NMT_ERR_FREE_TO_OPERATIONAL IS_ENABLED(CONFIG_CANOPENNODE_NMT_ERR_FREE_TO_OPERATIONAL)

/* NMT startup/control bits as plain defines you use in app/init glue */
#define CO_CONFIG_NMT_CONTROL                                                                      \
	((ZBIT(CO_NMT_STARTUP_TO_OPERATIONAL, CO_NMT_STARTUP_TO_OPERATIONAL) ? CO_NMT_STARTUP      \
									     : 0) |                \
	 (ZBIT(CO_NMT_ERR_ON_BUSOFF_HB, CO_NMT_ERR_ON_BUSOFF_HB) ? CO_NMT_ERR_ON_BUSOFF_HB : 0) |  \
	 (ZBIT(CO_NMT_ERR_ON_ERR_REG, CO_NMT_ERR_ON_ERR_REG) ? CO_NMT_ERR_ON_ERR_REG : 0) |        \
	 (ZBIT(CO_NMT_ERR_TO_STOPPED, CO_NMT_ERR_TO_STOPPED) ? CO_NMT_ERR_TO_STOPPED : 0) |        \
	 (ZBIT(CO_NMT_ERR_FREE_TO_OPERATIONAL, CO_NMT_ERR_FREE_TO_OPERATIONAL)                     \
		  ? CO_NMT_ERR_FREE_TO_OPERATIONAL                                                 \
		  : 0))

/* ---------- Heartbeat consumer ---------- */
#define CO_CONFIG_HB_CONS                                                                          \
	(ZBIT(CO_CONFIG_HB_CONS_ENABLE, CONFIG_CANOPENNODE_HB_CONS_ENABLE) |                       \
	 ZBIT(CO_CONFIG_HB_CONS_CALLBACK_CHANGE, CONFIG_CANOPENNODE_HB_CONS_CALLBACK_CHANGE) |     \
	 ZBIT(CO_CONFIG_HB_CONS_CALLBACK_MULTI, CONFIG_CANOPENNODE_HB_CONS_CALLBACK_MULTI) |       \
	 ZBIT(CO_CONFIG_HB_CONS_QUERY_FUNCT, CONFIG_CANOPENNODE_HB_CONS_QUERY_FUNCT) |             \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_HB_CONS_CALLBACK) |                  \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_HB_CONS_TIMERNEXT) |                    \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_HB_CONS_OD_DYNAMIC))

/* ---------- Node Guarding ---------- */
#define CO_CONFIG_NODE_GUARDING                                                                    \
	(ZBIT(CO_CONFIG_NODE_GUARDING_SLAVE_ENABLE,                                                \
	      CONFIG_CANOPENNODE_NODE_GUARDING_SLAVE_ENABLE) |                                     \
	 ZBIT(CO_CONFIG_NODE_GUARDING_MASTER_ENABLE,                                               \
	      CONFIG_CANOPENNODE_NODE_GUARDING_MASTER_ENABLE) |                                    \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_NODE_GUARDING_TIMERNEXT))

/* Count */
#ifdef CONFIG_CANOPENNODE_NODE_GUARDING_MASTER_COUNT
#define CO_CONFIG_NODE_GUARDING_MASTER_COUNT CONFIG_CANOPENNODE_NODE_GUARDING_MASTER_COUNT
#endif

/* ---------- Emergency ---------- */
#define CO_CONFIG_EM                                                                               \
	(ZBIT(CO_CONFIG_EM_PRODUCER, CONFIG_CANOPENNODE_EM_PRODUCER) |                             \
	 ZBIT(CO_CONFIG_EM_PROD_CONFIGURABLE, CONFIG_CANOPENNODE_EM_PROD_CONFIGURABLE) |           \
	 ZBIT(CO_CONFIG_EM_PROD_INHIBIT, CONFIG_CANOPENNODE_EM_PROD_INHIBIT) |                     \
	 ZBIT(CO_CONFIG_EM_HISTORY, CONFIG_CANOPENNODE_EM_HISTORY) |                               \
	 ZBIT(CO_CONFIG_EM_CONSUMER, CONFIG_CANOPENNODE_EM_CONSUMER) |                             \
	 ZBIT(CO_CONFIG_EM_STATUS_BITS, CONFIG_CANOPENNODE_EM_STATUS_BITS) |                       \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_EM_CALLBACK) |                       \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_EM_TIMERNEXT))

#define CO_CONFIG_EM_ERR_STATUS_BITS_COUNT CONFIG_CANOPENNODE_EM_ERR_STATUS_BITS_COUNT

/* Optional default conditions (you’ll map these to your CO_CONFIG_ERR_CONDITION_* usage) */
#define CO_CONFIG_ERR_CONDITION_CURRENT     IS_ENABLED(CONFIG_CANOPENNODE_ERR_CONDITION_CURRENT)
#define CO_CONFIG_ERR_CONDITION_VOLTAGE     IS_ENABLED(CONFIG_CANOPENNODE_ERR_CONDITION_VOLTAGE)
#define CO_CONFIG_ERR_CONDITION_TEMPERATURE IS_ENABLED(CONFIG_CANOPENNODE_ERR_CONDITION_TEMPERATURE)
#define CO_CONFIG_ERR_CONDITION_DEV_PROFILE IS_ENABLED(CONFIG_CANOPENNODE_ERR_CONDITION_DEV_PROFILE)

/* ---------- SDO server ---------- */
#define CO_CONFIG_SDO_SRV                                                                          \
	(ZBIT(CO_CONFIG_SDO_SRV_SEGMENTED, CONFIG_CANOPENNODE_SDO_SERVER_SEGMENTED) |              \
	 ZBIT(CO_CONFIG_SDO_SRV_BLOCK, CONFIG_CANOPENNODE_SDO_SERVER_BLOCK) |                      \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_SDO_SERVER_CALLBACK) |               \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_SDO_SERVER_TIMERNEXT) |                 \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_SDO_SERVER_OD_DYNAMIC))

#define CO_CONFIG_SDO_SRV_BUFFER_SIZE CONFIG_CANOPENNODE_SDO_SERVER_BUFFER_SIZE
#define CO_CONFIG_SDO_SRV_TIMEOUT_MS  CONFIG_CANOPENNODE_SDO_SERVER_TIMEOUT_MS

/* ---------- SDO client ---------- */
#define CO_CONFIG_SDO_CLI                                                                          \
	(ZBIT(CO_CONFIG_SDO_CLI_ENABLE, CONFIG_CANOPENNODE_SDO_CLIENT_ENABLE) |                    \
	 ZBIT(CO_CONFIG_SDO_CLI_SEGMENTED, CONFIG_CANOPENNODE_SDO_CLIENT_SEGMENTED) |              \
	 ZBIT(CO_CONFIG_SDO_CLI_BLOCK, CONFIG_CANOPENNODE_SDO_CLIENT_BLOCK) |                      \
	 ZBIT(CO_CONFIG_SDO_CLI_LOCAL, CONFIG_CANOPENNODE_SDO_CLIENT_LOCAL) |                      \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_SDO_CLIENT_CALLBACK) |               \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_SDO_CLIENT_TIMERNEXT) |                 \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_SDO_CLIENT_OD_DYNAMIC))

#define CO_CONFIG_SDO_CLI_BUFFER_SIZE CONFIG_CANOPENNODE_SDO_CLIENT_BUFFER_SIZE
#define CO_CONFIG_SDO_CLI_TIMEOUT_MS  CONFIG_CANOPENNODE_SDO_CLIENT_TIMEOUT_MS

/* ---------- TIME ---------- */
#define CO_CONFIG_TIME                                                                             \
	(ZBIT(CO_CONFIG_TIME_ENABLE, CONFIG_CANOPENNODE_TIME_ENABLE) |                             \
	 ZBIT(CO_CONFIG_TIME_PRODUCER, CONFIG_CANOPENNODE_TIME_PRODUCER) |                         \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_TIME_CALLBACK) |                     \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_TIME_OD_DYNAMIC))

/* ---------- SYNC / PDO ---------- */
#define CO_CONFIG_SYNC                                                                             \
	(ZBIT(CO_CONFIG_SYNC_ENABLE, CONFIG_CANOPENNODE_SYNC_ENABLE) |                             \
	 ZBIT(CO_CONFIG_SYNC_PRODUCER, CONFIG_CANOPENNODE_SYNC_PRODUCER) |                         \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_SYNC_CALLBACK) |                     \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_SYNC_TIMERNEXT) |                       \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_SYNC_OD_DYNAMIC))

#define CO_CONFIG_PDO                                                                              \
	(ZBIT(CO_CONFIG_RPDO_ENABLE, CONFIG_CANOPENNODE_RPDO_ENABLE) |                             \
	 ZBIT(CO_CONFIG_TPDO_ENABLE, CONFIG_CANOPENNODE_TPDO_ENABLE) |                             \
	 ZBIT(CO_CONFIG_RPDO_TIMERS_ENABLE, CONFIG_CANOPENNODE_RPDO_TIMERS_ENABLE) |               \
	 ZBIT(CO_CONFIG_TPDO_TIMERS_ENABLE, CONFIG_CANOPENNODE_TPDO_TIMERS_ENABLE) |               \
	 ZBIT(CO_CONFIG_PDO_SYNC_ENABLE, CONFIG_CANOPENNODE_PDO_SYNC_ENABLE) |                     \
	 ZBIT(CO_CONFIG_PDO_OD_IO_ACCESS, CONFIG_CANOPENNODE_PDO_OD_IO_ACCESS) |                   \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_PDO_CALLBACK) |                      \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_PDO_TIMERNEXT) |                        \
	 ZBIT(CO_CONFIG_FLAG_OD_DYNAMIC, CONFIG_CANOPENNODE_PDO_OD_DYNAMIC))

/* ---------- Storage ---------- */
#define CO_CONFIG_STORAGE (ZBIT(CO_CONFIG_STORAGE_ENABLE, CONFIG_CANOPENNODE_STORAGE_ENABLE))

/* Backend selection for your storage glue */
#define CO_STORAGE_BACKEND_SETTINGS IS_ENABLED(CONFIG_CANOPENNODE_STORAGE_BACKEND_SETTINGS)
#define CO_STORAGE_BACKEND_RAM      IS_ENABLED(CONFIG_CANOPENNODE_STORAGE_BACKEND_RAM)
#define CO_STORAGE_BACKEND_NONE     IS_ENABLED(CONFIG_CANOPENNODE_STORAGE_BACKEND_NONE)

/* ---------- LEDs ---------- */
#define CO_CONFIG_LEDs                                                                             \
	(ZBIT(CO_CONFIG_LEDS_ENABLE, CONFIG_CANOPENNODE_LEDS_ENABLE) |                             \
	 ZBIT(CO_CONFIG_LEDS_CALLBACK, CONFIG_CANOPENNODE_LEDS_CALLBACK) |                         \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_LEDS_TIMERNEXT))

/* ---------- SRDO / GFC ---------- */
#define CO_CONFIG_GFC                                                                              \
	(ZBIT(CO_CONFIG_GFC_ENABLE, CONFIG_CANOPENNODE_GFC_ENABLE) |                               \
	 ZBIT(CO_CONFIG_GFC_CONSUMER, CONFIG_CANOPENNODE_GFC_CONSUMER) |                           \
	 ZBIT(CO_CONFIG_GFC_PRODUCER, CONFIG_CANOPENNODE_GFC_PRODUCER))

#define CO_CONFIG_SRDO                                                                             \
	(ZBIT(CO_CONFIG_SRDO_ENABLE, CONFIG_CANOPENNODE_SRDO_ENABLE) |                             \
	 ZBIT(CO_CONFIG_SRDO_CHECK_TX, CONFIG_CANOPENNODE_SRDO_CHECK_TX) |                         \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_SRDO_CALLBACK) |                     \
	 ZBIT(CO_CONFIG_FLAG_TIMERNEXT, CONFIG_CANOPENNODE_SRDO_TIMERNEXT))

#define CO_CONFIG_SRDO_MINIMUM_DELAY CONFIG_CANOPENNODE_SRDO_MINIMUM_DELAY

/* ---------- LSS ---------- */
#define CO_CONFIG_LSS                                                                              \
	(ZBIT(CO_CONFIG_LSS_SLAVE, CONFIG_CANOPENNODE_LSS_SLAVE) |                                 \
	 ZBIT(CO_CONFIG_LSS_SLAVE_FASTSCAN_DIRECT_RESPOND,                                         \
	      CONFIG_CANOPENNODE_LSS_SLAVE_FASTSCAN_DIRECT_RESPOND) |                              \
	 ZBIT(CO_CONFIG_LSS_MASTER, CONFIG_CANOPENNODE_LSS_MASTER) |                               \
	 ZBIT(CO_CONFIG_FLAG_CALLBACK_PRE, CONFIG_CANOPENNODE_LSS_CALLBACK))

/* ---------- Gateway (CiA 309) ---------- */
#define CO_CONFIG_GTW                                                                              \
	(ZBIT(CO_CONFIG_GTW_MULTI_NET, CONFIG_CANOPENNODE_GTW_MULTI_NET) |                         \
	 ZBIT(CO_CONFIG_GTW_ASCII, CONFIG_CANOPENNODE_GTW_ASCII) |                                 \
	 ZBIT(CO_CONFIG_GTW_ASCII_SDO, CONFIG_CANOPENNODE_GTW_ASCII_SDO) |                         \
	 ZBIT(CO_CONFIG_GTW_ASCII_NMT, CONFIG_CANOPENNODE_GTW_ASCII_NMT) |                         \
	 ZBIT(CO_CONFIG_GTW_ASCII_LSS, CONFIG_CANOPENNODE_GTW_ASCII_LSS) |                         \
	 ZBIT(CO_CONFIG_GTW_ASCII_LOG, CONFIG_CANOPENNODE_GTW_ASCII_LOG) |                         \
	 ZBIT(CO_CONFIG_GTW_ASCII_ERROR_DESC, CONFIG_CANOPENNODE_GTW_ASCII_ERROR_DESC) |           \
	 ZBIT(CO_CONFIG_GTW_ASCII_PRINT_HELP, CONFIG_CANOPENNODE_GTW_ASCII_PRINT_HELP) |           \
	 ZBIT(CO_CONFIG_GTW_ASCII_PRINT_LEDS, CONFIG_CANOPENNODE_GTW_ASCII_PRINT_LEDS))

#define CO_CONFIG_GTW_BLOCK_DL_LOOP  CONFIG_CANOPENNODE_GTW_BLOCK_DL_LOOP
#define CO_CONFIG_GTWA_COMM_BUF_SIZE CONFIG_CANOPENNODE_GTWA_COMM_BUF_SIZE
#define CO_CONFIG_GTWA_LOG_BUF_SIZE  CONFIG_CANOPENNODE_GTWA_LOG_BUF_SIZE

/* ---------- CRC16 ---------- */
#define CO_CONFIG_CRC16                                                                            \
	(ZBIT(CO_CONFIG_CRC16_ENABLE, CONFIG_CANOPENNODE_CRC16_ENABLE) |                           \
	 ZBIT(CO_CONFIG_CRC16_EXTERNAL, CONFIG_CANOPENNODE_CRC16_EXTERNAL))

/* ---------- FIFO ---------- */
#define CO_CONFIG_FIFO                                                                             \
	(ZBIT(CO_CONFIG_FIFO_ENABLE, CONFIG_CANOPENNODE_FIFO_ENABLE) |                             \
	 ZBIT(CO_CONFIG_FIFO_ALT_READ, CONFIG_CANOPENNODE_FIFO_ALT_READ) |                         \
	 ZBIT(CO_CONFIG_FIFO_CRC16_CCITT, CONFIG_CANOPENNODE_FIFO_CRC16_CCITT) |                   \
	 ZBIT(CO_CONFIG_FIFO_ASCII_COMMANDS, CONFIG_CANOPENNODE_FIFO_ASCII_COMMANDS) |             \
	 ZBIT(CO_CONFIG_FIFO_ASCII_DATATYPES, CONFIG_CANOPENNODE_FIFO_ASCII_DATATYPES))

/* ---------- Trace ---------- */
#define CO_CONFIG_TRACE                                                                            \
	(ZBIT(CO_CONFIG_TRACE_ENABLE, CONFIG_CANOPENNODE_TRACE_ENABLE) |                           \
	 ZBIT(CO_CONFIG_TRACE_OWN_INTTYPES, CONFIG_CANOPENNODE_TRACE_OWN_INTTYPES))

/* ---------- Debug ---------- */
#define CO_CONFIG_DEBUG                                                                            \
	(ZBIT(CO_CONFIG_DEBUG_COMMON, CONFIG_CANOPENNODE_DEBUG_COMMON) |                           \
	 ZBIT(CO_CONFIG_DEBUG_SDO_CLIENT, CONFIG_CANOPENNODE_DEBUG_SDO_CLIENT) |                   \
	 ZBIT(CO_CONFIG_DEBUG_SDO_SERVER, CONFIG_CANOPENNODE_DEBUG_SDO_SERVER))

/* ---------- TX workqueue (Zephyr integration) ---------- */
#define CO_TX_WQ_STACK_SIZE CONFIG_CANOPENNODE_TX_WORKQUEUE_STACK_SIZE
#define CO_TX_WQ_PRIORITY   CONFIG_CANOPENNODE_TX_WORKQUEUE_PRIORITY

/* ---------- EDS path ---------- */
#define CO_EDS_FILE_PATH CONFIG_CANOPENNODE_EDS_FILE_PATH

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* ZEPHYR_MODULES_CANOPENNODE_CO_ZEPHYR_CONFIG_H */
